CC = gcc
LIB = -lsocket -lnsl

all: server client

server: myftpserver.c myftp.c
	${CC} -o server myftpserver.c myftp.c -pthread ${LIB}

client: myftpclient.c myftp.c
	${CC} -o client myftpclient.c myftp.c ${LIB}

clean:
	rm server
	rm client
