CC = gcc
LIB = -lisal

all: server client

server: myftpserver.c myftp.c
	${CC} -o myftpserver myftpserver.c myftp.c -lpthread ${LIB}

client: myftpclient.c myftp.c
	${CC} -o myftpclient myftpclient.c myftp.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient
